[package]
name = "macros_fixture"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
linter = ["macros/linter"]
problem = ["macros/problem"]

[dependencies]
macros = { path = "../macros", default-features = false }
