[workspace]
resolver = "2"
members = [
    "crates/*",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Andrew Kozin"]
license = "MIT"

[workspace.dependencies]

[workspace.lints.rust]