[package]
name = "macros_core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
inventory.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
