[package]
name = "core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tera = { workspace = true }
